[package]
name = "pallet-staking-benchmarking"
authors = ['Mangata team']
edition = '2018'
version = '0.1.0'

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0", default-features = false}
sp-runtime = { version = "2.0.0", default-features = false }
sp-staking = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-staking = { version = "2.0.0", default-features = false, path = "../" }
pallet-xyk = { version = "0.1.0", default-features = false, path = "../../xyk" }
orml-tokens = { path = '../../tokens', default-features = false, version = '0.3.1' }
mangata-primitives = { path = '../../../primitives/mangata', default-features = false, version = '0.1.0' }

sp-core = { default-features = false, version = '2.0.0' }
sp-npos-elections = { version = "2.0.0", default-features = false }
sp-io ={ version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false}
rand_chacha = { version = "0.2", default-features = false}

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-npos-elections/std",
	"sp-io/std",
    "mangata-primitives/std",
    "orml-tokens/std",
    "pallet-xyk/std",
	"rand_chacha/std",
]