[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/xyk',
    'runtime',
]

[patch.crates-io]
sc-block-builder = { default-features = false, version = '0.8.0', path = './client/block-builder' }
sc-service = { default-features = false, version = '0.8.0', path = './client/service' }
sc-consensus-babe = { default-features = false, version = '0.8.0', path = './client/consensus/babe' }
sc-network = { default-features = false, version = '0.8.0', path = './client/network' }
pallet-timestamp = { path = '/home/dev/substrate/frame/timestamp', default-features = false, version = '2.0.0' }
pallet-authorship = { path = './pallets/authorship', default-features = false, version = '2.0.0' }
