[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'pallets/*',
	'rpc/nonce',
	'runtime',
]

[patch."https://github.com/mangata-finance/mangata-node"]
pallet-xyk = { path = "./pallets/xyk" }
mangata-primitives = {path = "./primitives/mangata"}
pallet-issuance = { path = "./pallets/issuance" }

[patch."https://github.com/mangata-finance/moonbeam"]
parachain-staking =  { default-features = false, git = "https://github.com/mangata-finance//moonbeam.git", branch = "feature/tokenomics-impl" }
