[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'pallets/*',
	'rpc/nonce',
	'runtime',
]

[patch."https://github.com/mangata-finance/mangata-node"]
pallet-xyk = { path = "./pallets/xyk" }
mangata-primitives = {path = "./primitives/mangata"}

[patch."https://github.com/mangata-finance/substrate"]
pallet-authorship = {git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-bags-list = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-transaction-payment-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-transaction-payment = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-try-runtime = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-system-rpc-runtime-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-system = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-beefy = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-membership = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-benchmarking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-identity = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-session = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-aura = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-bounties = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-balances = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-authority-discovery = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-tips = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-election-provider-multi-phase = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-beefy-mmr = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
beefy-merkle-tree = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-scheduler = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-multisig = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-executive = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-im-online = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-treasury = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-utility = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-sudo = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-offences = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-democracy = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-grandpa = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-election-provider-support = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-collective = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-mmr-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-mmr = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-mmr-primitives = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-support = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-support-procedural-tools-derive = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-support-procedural-tools = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-support-procedural = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-nicks = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-staking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-staking-reward-curve = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-indices = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-babe = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-timestamp = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-elections-phragmen = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-proxy = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
pallet-vesting = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-informant = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-finality-grandpa-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-finality-grandpa = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
beefy-gadget-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
beefy-gadget = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-executor-wasmtime = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-executor-common = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-executor-wasmi = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-executor = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-network-gossip = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-transaction-pool-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-transaction-pool = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-tracing-proc-macro = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-tracing = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-client-db = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-sync-state-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-network = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-authority-discovery = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-utils = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-block-builder-ver = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-keystore = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-rpc-server = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-light = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-client-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-service = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-basic-authorship-ver = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-block-builder = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-rpc-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-chain-spec-derive = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-chain-spec = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-proposer-metrics = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-peerset = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-basic-authorship = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-offchain = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-state-db = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-allocator = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-aura = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-uncles = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-epochs = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-slots = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-babe-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-consensus-babe = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-cli = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sc-telemetry = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
fork-tree = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
substrate-wasm-builder = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
try-runtime-cli = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
frame-benchmarking-cli = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
substrate-frame-rpc-system = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
remote-externalities = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
substrate-build-script-utils = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
substrate-prometheus-endpoint = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
substrate-test-client = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-panic-handler = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-inherents = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-authorship = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-storage = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-std = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-finality-grandpa = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
beefy-primitives = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-version-proc-macro = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-version = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-transaction-pool = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-ver = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-tracing = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-database = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-debug-derive = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-session = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
extrinsic-shuffler = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
ver-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-core = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-keyring = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-authority-discovery = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-tasks = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-runtime-interface-proc-macro = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-runtime-interface = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-arithmetic = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-keystore = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-api-proc-macro = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-api = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-rpc = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-maybe-compressed-blob = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-transaction-storage-proof = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-state-machine = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-block-builder = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-wasm-interface = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-npos-elections = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-npos-elections-solution-type = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-application-crypto = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-serializer = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-offchain = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-staking = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-trie = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-blockchain = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-externalities = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-consensus = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-consensus-aura = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-consensus-slots = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-consensus-vrf = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-consensus-babe = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-timestamp = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-runtime = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
sp-io = { git = "https://github.com/mangata-finance//substrate", branch = "feature/runtime_seed_validation"}
