[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/xyk',
    'runtime',
]

[patch.crates-io]
artemis-asset = { git = 'https://github.com/mangata-finance/snowbridge', branch="mangata-dev" }
artemis-core = { git = 'https://github.com/mangata-finance/snowbridge', branch="mangata-dev" }
artemis-erc20-app = { git = 'https://github.com/mangata-finance/snowbridge', branch="mangata-dev" }
artemis-eth-app = { git = 'https://github.com/mangata-finance/snowbridge', branch="mangata-dev" }
extrinsic-info-runtime-api = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
frame-executive = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
orml-tokens = { git = 'https://github.com/mangata-finance/open-runtime-module-library', branch="mangata-dev" }
pallet-authorship = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
pallet-random-seed = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
pallet-staking = { path="pallets/staking"}
pallet-timestamp = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
pallet-treasury = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
pallet-verifier = { git = 'https://github.com/mangata-finance/snowbridge', branch="mangata-dev" }
random-seed-runtime-api = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev'}
sc-basic-authorship = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev' }
sc-block-builder = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev' }
sc-consensus-babe = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev' }
sc-service = { git = 'https://github.com/mangata-finance/substrate', branch='mangata-dev' }
