[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/xyk',
    'runtime',
]
[patch."https://github.com/mangata-finance/substrate"]
frame-metadata = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-authorship = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-transaction-payment-rpc = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-transaction-payment = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-system-rpc-runtime-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-system = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-benchmarking = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-session = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-balances = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-authority-discovery = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
random-seed-runtime-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-random-seed = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-executive = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-treasury = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-sudo = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-offences = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-grandpa = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-randomness-collective-flip = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-support = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-support-procedural-tools-derive = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-support-procedural-tools = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-support-procedural = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-staking = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-staking-reward-curve = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-finality-tracker = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-babe = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
pallet-timestamp = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-informant = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-finality-grandpa = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-executor-wasmtime = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-executor-common = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-executor-wasmi = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-executor = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-network-gossip = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-transaction-graph = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-transaction-pool = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-tracing = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-client-db = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
extrinsic-shuffler = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-network = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-authority-discovery = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-keystore = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-rpc-server = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-light = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-client-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-rpc = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-service = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-block-builder = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-rpc-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-chain-spec-derive = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-chain-spec = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-proposer-metrics = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-peerset = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-basic-authorship = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-offchain = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-state-db = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-consensus = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-consensus-uncles = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-consensus-epochs = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-consensus-slots = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-consensus-babe = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-cli = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sc-telemetry = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
fork-tree = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
frame-benchmarking-cli = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-frame-rpc-system = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-build-script-utils = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-prometheus-endpoint = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-wasm-builder-runner = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-test-utils-derive = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
substrate-test-utils = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-panic-handler = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-inherents = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-authorship = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-storage = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-std = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-finality-grandpa = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-ignore-tx = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-version = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-transaction-pool = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-tracing = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-database = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-debug-derive = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
extrinsic-info-runtime-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-session = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-core = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-keyring = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-authority-discovery = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-utils = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-runtime-interface-proc-macro = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-runtime-interface = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-arithmetic = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-api-proc-macro = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-api = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-rpc = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-state-machine = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-block-builder = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-wasm-interface = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-npos-elections-compact = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-npos-elections = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-application-crypto = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-serializer = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-chain-spec = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-offchain = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-staking = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-trie = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-blockchain = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-allocator = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-externalities = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-finality-tracker = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-consensus = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-consensus-slots = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-consensus-vrf = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-consensus-babe = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-timestamp = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-runtime = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
sp-io = { git="https://github.com/mateuszaaa/substrate", branch="feature/enable_block_validations" }
