[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'pallets/*',
	'runtime',
]

[patch."https://github.com/mangata-finance/open-runtime-module-library"]
orml-tokens = { path = "../open-runtime-module-library/tokens" }
orml-traits = { path = "../open-runtime-module-library/traits" }


[patch."https://github.com/mangata-finance/mangata-node"]
mangata-primitives = {path = "../mangata-node-subs-v3/primitives/mangata"}
# mangata-primitives = {git = "https://github.com/mangata-finance/mangata-node/primitives/mangata", branch = "mangata-dev"}
