[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'pallets/*',
	'rpc/nonce',
	'runtime',
]

[patch."https://github.com/mangata-finance/mangata-node"]
pallet-xyk = { path = "./pallets/xyk" }
mangata-primitives = {path = "./primitives/mangata"}

[patch."https://github.com/mangata-finance/substrate"]
pallet-authorship = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-bags-list = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-transaction-payment-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-transaction-payment = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-try-runtime = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-system-rpc-runtime-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-system = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-beefy = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-membership = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-benchmarking = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-identity = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-session = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-aura = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-bounties = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-balances = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-authority-discovery = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-tips = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-election-provider-multi-phase = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-beefy-mmr = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
beefy-merkle-tree = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-scheduler = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-multisig = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-executive = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-im-online = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-treasury = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-utility = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-sudo = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-offences = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-democracy = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-grandpa = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-election-provider-support = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-collective = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-mmr-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-mmr = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-mmr-primitives = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-support = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-support-procedural-tools-derive = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-support-procedural-tools = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-support-procedural = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-nicks = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-staking = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-staking-reward-curve = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-indices = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-babe = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-timestamp = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-elections-phragmen = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-proxy = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
pallet-vesting = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-informant = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-finality-grandpa-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-finality-grandpa = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
beefy-gadget-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
beefy-gadget = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-executor-wasmtime = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-executor-common = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-executor-wasmi = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-executor = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-network-gossip = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-transaction-pool-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-transaction-pool = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-tracing-proc-macro = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-tracing = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-client-db = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-sync-state-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-network = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-authority-discovery = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-utils = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-block-builder-ver = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-keystore = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-rpc-server = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-light = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-client-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-service = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-basic-authorship-ver = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-block-builder = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-rpc-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-chain-spec-derive = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-chain-spec = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-proposer-metrics = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-peerset = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-basic-authorship = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-offchain = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-state-db = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-allocator = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-aura = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-uncles = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-epochs = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-slots = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-babe-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-consensus-babe = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-cli = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sc-telemetry = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
fork-tree = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
substrate-wasm-builder = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
try-runtime-cli = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
frame-benchmarking-cli = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
substrate-frame-rpc-system = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
remote-externalities = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
substrate-build-script-utils = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
substrate-prometheus-endpoint = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
substrate-test-client = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-panic-handler = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-inherents = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-authorship = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-storage = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-std = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-finality-grandpa = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
beefy-primitives = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-version-proc-macro = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-version = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-transaction-pool = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-ver = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-tracing = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-database = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-debug-derive = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-session = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
extrinsic-shuffler = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
ver-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-core = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-keyring = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-authority-discovery = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-tasks = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-runtime-interface-proc-macro = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-runtime-interface = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-arithmetic = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-keystore = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-api-proc-macro = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-api = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-rpc = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-maybe-compressed-blob = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-transaction-storage-proof = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-state-machine = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-block-builder = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-wasm-interface = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-npos-elections = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-npos-elections-solution-type = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-application-crypto = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-serializer = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-offchain = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-staking = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-trie = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-blockchain = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-externalities = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-consensus = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-consensus-aura = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-consensus-slots = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-consensus-vrf = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-consensus-babe = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-timestamp = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-runtime = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
sp-io = { git="https://github.com/mangata-finance//substrate", branch="feature/multi_signature_supprt" }
