[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'runtime',
]

[patch.crates-io]
sc-block-builder = { default-features = false, version = '0.8.0', path = './client/block-builder' }
