version: "3.7"
networks:
    test_net:
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24

services:
  relay_alice:
    environment:
      - ${RUST_LOG:-info}
    image: parity/polkadot:v0.9.12
    command:
      - "--alice"
      - "--validator"
      - "--tmp"
      - "--port=30333"
      - "--ws-port=9944"
      - "--chain=/etc/mangata/spec.json"
      - "--unsafe-ws-external"
      - "--rpc-port=40333"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
    volumes:
      - ./config:/etc/mangata
    networks:
        test_net:
          ipv4_address: 10.0.0.2

  relay_bob:
    image: parity/polkadot:v0.9.12
    environment:
      - ${RUST_LOG:-info}
    command:
      - "--bob" 
      - "--validator" 
      - "--tmp" 
      - "--port=30333" 
      - "--ws-port=9944" 
      - "--chain=/etc/mangata/spec.json" 
      - "--bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp" 
      - "--unsafe-ws-external" 
      - "--unsafe-rpc-external" 
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000002"
    volumes:
      - ./config:/etc/mangata
    networks:
        test_net:
          ipv4_address: 10.0.0.3


  register:
    # build:
    #   context: ../../
    #   dockerfile: devops/dockerfiles/node-and-runtime/para.dockerfile
    image: matmangata/mat-registrator:alpha
    command: bash -c "sleep 10s && node index.js"
    environment:
      - STATE_FILE=/config/genesis-state
      - WASM_FILE=/config/genesis-wasm
      - COLLATOR_ADDR=ws://10.0.0.2:9944
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.4

  # export:
  #   image: "mangatasolutions/mangata-node:v4-dev"
  #   entrypoint: ""
  #   command: >
  #     bash -xc "
  #     /mangata/node export-genesis-state > /etc/mangata/genesis-state;
  #     /mangata/node export-genesis-wasm > /etc/mangata/genesis-wasm;
  #     du /etc/mangata/genesis-state;
  #     md5sum /etc/mangata/genesis-state;
  #     du /etc/mangata/genesis-wasm;
  #     md5sum /etc/mangata/genesis-wasm;
  #     "
  #   volumes:
  #     - ./config:/etc/mangata
  #   networks:
  #       test_net:
  #         ipv4_address: 10.0.0.11


  para_alice:
    image: "mangatasolutions/mangata-node:latest"
    environment:
      - ${RUST_LOG:-info}
    entrypoint: ""
    command: >
      bash -xc "
      /mangata/node export-genesis-state > /etc/mangata/genesis-state;
      /mangata/node export-genesis-wasm > /etc/mangata/genesis-wasm;
      /mangata/node
      --alice
      --collator
      --force-authoring
      --tmp
      --port=30333
      --ws-port=9944
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000003
      --
      --execution=wasm
      --chain=/etc/mangata/spec.json
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      " 
    volumes:
      - ./config:/etc/mangata
    networks:
        test_net:
          ipv4_address: 10.0.0.5

  para_bob:
    image: "mangatasolutions/mangata-node:latest"
    environment:
      - ${RUST_LOG:-info}
    entrypoint: ""
    command:
      - "/mangata/node"
      - "--bob"
      - "--collator"
      - "--force-authoring"
      - "--tmp"
      - "--port=30333"
      - "--ws-port=9944"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000004"
      - "--bootnodes=/dns/para_alice/tcp/30333/p2p/12D3KooWKpDhPnax8CyJvVh77Z5T84a8EWZvY7c9Z7pZ1tk6sLBD"
      - "--"
      # relay
      - "--execution=wasm"
      - "--chain=/etc/mangata/spec.json"
      - "--bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp" 
    volumes:
      - ./config:/etc/mangata
    networks:
        test_net:
          ipv4_address: 10.0.0.6

  # ui:
  #   build:
  #     context: ../../
  #     dockerfile: devops/dockerfiles/node-and-runtime/ui.dockerfile
  #   ports:
  #     - 3000:3000
  #   networks:
  #       test_net:
  #         ipv4_address: 10.0.0.10


  # export:
  #   image: "mangatasolutions/mangata-node:v4-dev"
  #   entrypoint: ""
  #   command: >
  #     bash -xc "
  #     /mangata/node export-genesis-state > /etc/mangata/genesis-state;
  #     /mangata/node export-genesis-wasm > /etc/mangata/genesis-wasm;
  #     du /etc/mangata/genesis-state;
  #     md5sum /etc/mangata/genesis-state;
  #     du /etc/mangata/genesis-wasm;
  #     md5sum /etc/mangata/genesis-wasm;
  #     "
  #   volumes:
  #     - ./config:/etc/mangata
  #   networks:
  #       test_net:
  #         ipv4_address: 10.0.0.11

