version: "3.7"
networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  relay_alice:
    environment:
      - ${RUST_LOG:-info}
    image: p1k1m4n/polkadot-fast-runtime:0.9.18
    command: >
      --alice 
      --validator 
      --base-path /tmp/node
      --chain /etc/mangata/rococo-local.json 
      --port 30333 
      --ws-port 9944
      --unsafe-ws-external
      --rpc-port=40333
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000001
    volumes:
      - ./config:/etc/mangata
    ports:
      - 9944:9944
      - 9933:9933

    networks:
      test_net:
        ipv4_address: 10.0.0.2

  relay_bob:
    image: p1k1m4n/polkadot-fast-runtime:0.9.18
    environment:
      - ${RUST_LOG:-info}
    command: >
      --bob 
      --validator 
      --base-path /tmp/node
      --chain /etc/mangata/rococo-local.json 
      --bootnodes /dns/relay_alice/tcp/30333/p2p/12D3KooWLLuwx329jiPHfFgbiB2cfymTGtGpu6wBoqDTekxJYRqR
      --port 30333
      --ws-port 9944
      --node-key=0000000000000000000000000000000000000000000000000000000000000002
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
    volumes:
      - ./config:/etc/mangata
    networks:
      test_net:
        ipv4_address: 10.0.0.3

  register:
    image: mangatasolutions/parachain-register:0.1
    command: bash -c "sleep 10s && node index.js"
    environment:
      - STATE_FILE=/config/genesis-state
      - WASM_FILE=/config/genesis-wasm
      - COLLATOR_ADDR=ws://relay_alice:9944
    volumes:
      - ./config:/config
    networks:
      test_net:
        ipv4_address: 10.0.0.4

  para_alice:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    environment:
      - ${RUST_LOG:-info}
      - RUST_BACKTRACE=1
      - LD_PRELOAD=${LD_PRELOAD}
    entrypoint: ""
    command: >
      bash -xc "
      /mangata/node export-genesis-state > /etc/mangata/genesis-state;
      /mangata/node export-genesis-wasm > /etc/mangata/genesis-wasm;
      /mangata/node
      --alice 
      --collator 
      --force-authoring 
      --chain=local
      --base-path /tmp/node
      --port 30333 
      --ws-port 9944 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000003
      -- 
      --execution wasm 
      --chain /etc/mangata/rococo-local.json 
      --port 30334
      --ws-port 8844
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      "
    volumes:
      - ./config:/etc/mangata
      # - ./para_alice:/tmp/node
    ports:
      - 9955:9944
      - 9966:9933
    networks:
      test_net:
        ipv4_address: 10.0.0.5

  para_bob:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    environment:
      - ${RUST_LOG:-info}
      - LD_PRELOAD=${LD_PRELOAD}
    command: >
      --bob 
      --collator 
      --force-authoring 
      --chain=local
      --base-path /tmp/node
      --port=30333 
      --ws-port=9944 
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors=all
      --node-key=0000000000000000000000000000000000000000000000000000000000000003
      --bootnodes=/dns/para_alice/tcp/30333/p2p/12D3KooWKpDhPnax8CyJvVh77Z5T84a8EWZvY7c9Z7pZ1tk6sLBD
      -- 
      --execution wasm 
      --chain /etc/mangata/rococo-local.json 
      --port 30334
      --ws-port 8844
      --bootnodes=/dns/relay_alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    volumes:
      - ./config:/etc/mangata
        # - ./para_bob:/tmp/node
    networks:
      test_net:
        ipv4_address: 10.0.0.6
    cap_add:
      - SYS_ADMIN
