version: "3.7"
networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  gen-para:
    image: ${PARACHAIN_DOCKER_IMAGE:-mangatasolutions/mangata-node:latest}
    entrypoint: ""
    command: >
      bash -xec "
      /mangata/node export-genesis-state --chain=${PARA_CHAIN:-mangata-rococo-local-testnet} > /etc/mangata/state &&
      /mangata/node export-genesis-wasm --chain=${PARA_CHAIN:-mangata-rococo-local-testnet} > /etc/mangata/wasm &&
      RUST_LOG=error /mangata/node build-spec --chain=${PARA_CHAIN:-mangata-rococo-local-testnet} --disable-default-bootnode --raw 2>/dev/null > /etc/mangata/para-spec.json
      "
    volumes:
      - ./config:/etc/mangata
    networks:
      test_net:
        ipv4_address: 10.0.0.30

  gen-relay:
    image: parity/polkadot:v0.9.16
    entrypoint: ""
    command: >
      bash -xec "
      /usr/bin/polkadot build-spec --chain=rococo-local --disable-default-bootnode --raw 2>/dev/null > /etc/mangata/relay-spec.json
      "
    volumes:
      - ./config:/etc/mangata
    networks:
      test_net:
        ipv4_address: 10.0.0.31

