[package]
authors = ['Mangata team']
edition = '2018'
name = 'pallet-xyk'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
serde = { version = "1.0.111", optional = true }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
orml-tokens = { path = '../tokens', default-features = false, version = '0.3.1' }
sp-runtime = { default-features = false, version = '2.0.0' }
sp-core = { default-features = false, version = '2.0.0' }
sp-std = { version = "2.0.0", default-features = false }
mangata-primitives = { path = '../../primitives/mangata', default-features = false, version = '0.1.0' }
sp-arithmetic = { default-features = false, version = '2.0.0' }



[dev-dependencies]

sp-io = { default-features = false, version = '2.0.0' }

[features]
default = ['std']
std = [
	"serde",
    'codec/std',
    "sp-std/std",
    'frame-support/std',
    'frame-system/std',
]
