[package]
name = "mangata-rpc-nonce"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" }
codec = { package = "parity-scale-codec", version = "2.0.0" }
futures = "0.3.16"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
log = "0.4.8"
sp-runtime = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" }
frame-system-rpc-runtime-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
sp-core ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
sp-blockchain ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
ver-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
sc-transaction-pool-api ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
sp-block-builder ={ version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" } 
sc-rpc-api ={ version = "0.10.0-dev", git = "https://github.com/mangata-finance/substrate" } 

[dev-dependencies]
# substrate-test-runtime-client = { version = "2.0.0", git = "https://github.com/mangata-finance/substrate" }
sp-tracing = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/mangata-finance/substrate" }
