---
- name: create mangata deployment directory
  file:
    path: "{{ mangata_directory_name }}" 
    state: directory  

- name: copy mangata deployment directory recursively to its path 
  copy:
    src: "../devops/"
    dest: "{{ mangata_directory_name }}" 
    directory_mode: yes

#- name: start the mangata node
#  shell: "docker run -itd mangatasolutions/mangata-node:{{ mangata_image_version }}" 
    
#- name: Copying template files to designated directories 
#  template: src=templates/{{ item.name }}.j2 dest={{ item.path }}
#  loop: "{{ stackcomponents }}" 
#  notify: restart docker

#- name: stopping the mangata node if needed
#  shell: "docker-compose -f /home/{{ mangata_user }}/{{ deployment_path }}/docker-compose.yml down" 


- name: running the mangata node 
  shell: "docker-compose -f {{ deployment_path }}/multivalidator-dev-chainspec-patched-updated.json up -d"
