[package]
name = "sc-consensus-babe"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "BABE consensus algorithm for substrate"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-consensus-babe"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"] }
sp-consensus-babe = "0.8.0"
sp-core = "2.0.0"
sp-application-crypto = "2.0.0"
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
serde = { version = "1.0.104", features = ["derive"] }
sp-version = "2.0.0"
sp-io = "2.0.0"
sp-inherents = "2.0.0"
sp-timestamp = "2.0.0"
sc-telemetry = "2.0.0"
sc-keystore = "2.0.0"
sc-client-api = "2.0.0"
sc-consensus-epochs = "0.8.0"
sp-api = "2.0.0"
sp-block-builder = "2.0.0"
sp-blockchain = "2.0.0"
sp-consensus = "0.8.0"
sp-consensus-vrf = "0.8.0"
sc-consensus-uncles = "0.8.0"
sc-consensus-slots = "0.8.0"
sp-runtime = "2.0.0"
sp-utils = "2.0.0"
fork-tree = "2.0.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.8.0"}
futures = "0.3.4"
futures-timer = "3.0.1"
parking_lot = "0.10.0"
log = "0.4.8"
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated"] }
rand = "0.7.2"
merlin = "2.0"
pdqselect = "0.1.0"
derive_more = "0.99.2"
retain_mut = "0.1.1"
random-seed-runtime-api = {path="../../../pallets/random-seed/runtime-api", version="2.0.0"}
pallet-random-seed = { path='../../../pallets/random-seed', version='2.0.0' }

[dev-dependencies]
sp-keyring = "2.0.0"
sp-tracing = "2.0.0"
sc-executor = "0.8.0"
sc-network = "0.8.0"
sc-network-test = "0.8.0"
sc-service = { version = "0.8.0", default-features = false, path = "../../service" }
#substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
sc-block-builder = { version = "0.8.0", path = "../../block-builder" }
rand_chacha = "0.2.2"
tempfile = "3.1.0"

[features]
test-helpers = []
