[package]
name = "mangata-primitives"
version = "0.1.0"
authors = ['Mangata team']
edition = "2018"

[dependencies]
sp-core = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", default-features = false, branch = "mangata-dev" }

[features]
default = ["std"]
std = [
]
