name: Deployment

#on: 
#  pull_request:
#    branches: [*]

on:
    push: 
      branches: 
        - feature/second-interview 
#      paths:
#        - "terraform/**"  
  
env:
  DEPLOY_DIR: "terraform/"
  AWS_ACCESS_KEY_ID: ${{ secrets.Terraform_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.Terraform_SECRET_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: check version
      id: version
      run: terraform -version
    - name: Terraform Init
      id: init
      run: terraform init -backend
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -lock=false
      continue-on-error: true
    - name: apply the templates
      run: terraform apply --auto-approve -lock=false
    - name: list inventories
      run: |
          ls -alh ${GITHUB_WORKSPACE}/ansible/files/
    #- name: stashing the sshkey
    #  run: |
    #      git add ${GITHUB_WORKSPACE}/ansible/files/sshkey.pem
    #      git stash push -m "sshkey" ${GITHUB_WORKSPACE}/ansible/files/sshkey.pem
    #- name: pwd
    #  run: |
    #      pwd           
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: sshkey.pem
    #    path: ./sshkey.pem

      
  #deploy-configmanagement:

#    runs-on: ubuntu-latest
#    needs: deploy-infrastructure
    defaults:
      run:
        working-directory: ./ansible
      
    steps:
    #- name: checkout Repo
    #  uses: actions/checkout@v3
    #- uses: actions/download-artifact@v3
    #  with:
    #    name: sshkey.pem
    #    path: ${GITHUB_WORKSPACE}/ansible/files/sshkey.pem
    #- name: stashing the sshkey
    #  run: |
    #    git stash pop
    - name: list ssh key directory
      run: |
          ls -alh ./ansible/files
    - name: set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: working directory
      run: |
          pwd
    - name: list
      run: |
        ls -alh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: run exporters playbook
      run: |
        ansible-playbook -i inventories/inventory.yml playbook.yml