name: Deployment

#on: 
#  pull_request:
#    branches: [*]

on:
    push: 
      branches: 
        - feature/second-interview 
#      paths:
#        - "terraform/**"  
  
env:
  DEPLOY_DIR: "terraform/"
  AWS_ACCESS_KEY_ID: ${{ secrets.Terraform_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.Terraform_SECRET_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: check version
      id: version
      run: terraform -version
    - name: Terraform Init
      id: init
      run: terraform init -backend
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -lock=false
      continue-on-error: true
    - name: apply the templates
      run: terraform apply --auto-approve -lock=false
    - name: saving dynamically generated inventory
      uses: actions/upload-artifact@v2
      with:
        name: playbooks
        path: ${GITHUB_WORKSPACE}/ansible

  linting-configmanagement:
    name: Lint Ansible files
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    defaults:
      run:
        working-directory: ./ansible
      
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: playbooks
        path: ${GITHUB_WORKSPACE}/ansible
    - name: Linting
      uses: ansible/ansible-lint-action@c37fb7b4bda2c8cb18f4942716bae9f11b0dc9bc
      with:
        targets: |
          inventories/inventory.yml
          playbook.yml
        args: "-c ansible/.ansible-lint"
      
  #deploy-configmanagement:

#    runs-on: ubuntu-latest
#    needs: deploy-infrastructure
    #defaults:
    #  run:
    #    working-directory: ./ansible
      
    #steps:
    #- name: checkout Repo
    #  uses: actions/checkout@v3
    #- uses: actions/download-artifact@v3
    #  with:
    #    name: sshkey.pem
    #    path: ${GITHUB_WORKSPACE}/ansible/files/sshkey.pem
    #- name: stashing the sshkey
    #  run: |
    #    git stash pop
    - name: set up python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      working-directory: ./ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests 
        pip list
    - name: run exporters playbook
      working-directory: ./ansible
      run: |
        ansible-playbook -i inventories/inventory.yml --extra-vars="ansible_ssh_private_key_file=${GITHUB_WORKSPACE}/ansible/files/sshkey.pem" playbook.yml