name: Release

on: 
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mangatasolutions/mangata-node
          tags: |
            type=semver,pattern={{version}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull kusama image
        run: |
          docker pull mangatasolutions/mangata-node:kusama-${{ github.sha }}
          docker tag mangatasolutions/mangata-node:kusama-${{ github.sha }} mangatasolutions/mangata-node:kusama-${{ steps.meta.outputs.tags }}
      -
        name: Push kusama image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mangatasolutions/mangata-node:kusama-${{ steps.meta.outputs.tags }}]
      -
        name: Pull rococo image
        run: |
          docker pull mangatasolutions/mangata-node:rococo${{ github.sha }}
          docker tag mangatasolutions/mangata-node:rococo${{ github.sha }} mangatasolutions/mangata-node:rococo-${{ steps.meta.outputs.tags }}
      -
        name: Build rococo image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mangatasolutions/mangata-node:rococo-${{ steps.meta.outputs.tags }}
